server:
  port: 8080

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL} # default to "bazaar" if not set
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update      # still auto-update schema during container development
    show-sql: false
    open-in-view: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, info, prometheus
  endpoint:
    health:
      show-details: when_authorized

bazaar:
  poll:
    enabled: true
    interval-ms: 30000 # 30 seconds
  retention:
    enabled: true
    interval-hours: 24 # 1 day

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html