server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json,application/javascript,text/css,text/html

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none                        # no schema changes at runtime
    open-in-view: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  flyway:
    enabled: true                           # enable Flyway migrations
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, info, prometheus
  endpoint:
    health:
      show-details: always                  # more detail in prod health checks

skyblock:
  bazaar:
    poll:
      enabled: true
      interval-seconds: 60 # 1 minute
    processing:
      price-move-threshold: 0.2 # 0.2%
      max-snapshot-gap-min: 15 # 5 minutes
      hourly:
        enabled: true
    retention:
      enabled: false
      interval-hours: 24 # 1 day
  catalog:
    enabled: true
    refresh-days: 7
    cron: "0 0 3 * * *"   # 03:00 every day


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html