server:
  port: 8080
#  ssl:
#    key-store: file:/config/keystore.p12
#    key-store-password: ${KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: tomcat
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json,application/javascript,text/css,text/html

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL} # default to "bazaar" if not set
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 20   # default is 10
      minimumIdle: 5        # optional: keep a warm floor
  jpa:
    hibernate:
      ddl-auto: update      # use Hibernate auto-update, not Flyway
    open-in-view: false
    properties:
      #            hibernate.cache.use_second_level_cache: false
      #            hibernate.cache.use_query_cache: false
      #            hibernate.format_sql: true
      #            hibernate.generate_statistics: true
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.default_batch_fetch_size: 50
      #        show-sql: true
      show-sql: false
  flyway:
    enabled: false          # disable Flyway, use Hibernate instead
  task:
    execution:
      pool:
        max-size: 12     # example: double the default on 2 cores
        core-size: 4    # optional: keep some threads always alive
#  security:
#    user:
#      name: ${ADMIN_USER:admin}
#      password: ${ADMIN_PASSWORD:?required}  # fail fast if not set

logging:
  level:
    org.hibernate.persister.entity.AbstractEntityPersister: ERROR

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.stat: DEBUG
#
#reactor:
#  netty:
#    ioWorkerCount: 4  # leave default unless you have proof

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, info, prometheus
  endpoint:
    health:
      show-details: when_authorized

skyblock:
  bazaar:
    poll:
      enabled: true
      interval-seconds: 60 # 1 minute
    processing:
      price-move-threshold: 0.2 # 0.2%
      max-snapshot-gap-min: 15 # 5 minutes
      hourly:
        enabled: true
    retention:
      enabled: true
      interval-days: 30 # 30 days
    finance:
      metrics:
        enabled: true
        interval-minutes: 60 # 1 hour
  catalog:
    enabled: true
    refresh-days: 7
    cron: "0 0 3 * * *"   # 03:00 every day

resilience4j.ratelimiter:
  instances:
    bazaarEndpoint:
      limitForPeriod: 200     # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full
    skyblockCatalog:
      limitForPeriod: 100    # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full
    subscriptionEndpoint:
      limitForPeriod: 50     # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: https://localhost:3001,https://bazaar.example.com

# --- Feature Flags / Toggles ---
# Controle explícito para evitar ativação não intencional em ambientes novos.
billing:
  enabled: false   # habilitar somente quando Stripe configurado

# Auth (resource server) - configurar em runtime
# COMO PREENCHER (Auth0):
#   Domain Auth0           -> modern-bazaar.eu.auth0.com (exemplo)
#   issuer-uri (iss)       -> https://<Domain>/   (ATENÇÃO: barra final)
#   jwks-uri               -> https://<Domain>/.well-known/jwks.json
#   audience (Identifier)  -> criar em Auth0: Applications > APIs > Create API
#                              Identifier exemplo: https://modern-bazaar.api
# FRONTEND deve pedir token com esse audience senão aud não bate.
# Client ID / Client Secret NÃO entram aqui; só usados pelo frontend para obter o token.
# Se ainda não criou a API em Auth0, crie antes de definir AUTH_AUDIENCE.
# Para desenvolvimento sem Auth0 real defina: auth.mock-enabled=true e deixe os outros vazios.
auth:
  mock-enabled: false  # true: usa decoder stub quando jwks-uri ausente
  jwks-uri: ${AUTH_JWKS_URI:}
  issuer-uri: ${AUTH_ISSUER_URI:}
  audience: ${AUTH_AUDIENCE:}

# Stripe
#   STRIPE_WEBHOOK_SECRET = signing secret do endpoint de webhook (Dashboard > Developers > Webhooks)
#   Para implementar checkout depois adicionar também STRIPE_API_KEY.
stripe:
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
