server:
  port: 8080

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL} # default to "bazaar" if not set
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update      # still auto-update schema during container development
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized