server:
  port: 8080
#  ssl:
#    key-store: file:/config/keystore.p12
#    key-store-password: ${KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: tomcat
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json,application/javascript,text/css,text/html

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL} # default to "bazaar" if not set
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update      # still auto-update schema during container development
    show-sql: false
    open-in-view: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 1
#  security:
#    user:
#      name: ${ADMIN_USER:admin}
#      password: ${ADMIN_PASSWORD:?required}  # fail fast if not set

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, info, prometheus
  endpoint:
    health:
      show-details: when_authorized

skyblock:
  bazaar:
    poll:
      enabled: true
      interval-seconds: 60 # 1 minute
    processing:
      price-move-threshold: 0.2 # 0.2%
      max-snapshot-gap-min: 15 # 5 minutes
      hourly:
        enabled: true
    retention:
      enabled: false
      interval-hours: 24 # 1 day
  catalog:
    enabled: true
    refresh-days: 7
    cron: "0 0 3 * * *"   # 03:00 every day

resilience4j.ratelimiter:
  instances:
    bazaarEndpoint:
      limitForPeriod: 200     # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full
    skyblockCatalog:
      limitForPeriod: 100    # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: https://localhost:3001,https://bazaar.example.com
  allowed-methods: GET,POST,PUT,DELETE
