server:
  port: 8080

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none                        # no schema changes at runtime
    open-in-view: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  flyway:
    enabled: true                           # enable Flyway migrations
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, info, prometheus
  endpoint:
    health:
      show-details: always                  # more detail in prod health checks

bazaar:
  poll:
    enabled: true
    interval-seconds: 60 # 1 minute
  retention:
    enabled: true
    interval-hours: 24 # 1 day

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html