server:
  port: 8080

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update      # dev only; auto-create/alter tables
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, prometheus   # Actuator endpoints

bazaar:
  poll:
#    interval-ms: 2000 # 2 seconds
    interval-ms: 30000 # 30 seconds
  retention-days: 2 # 2 days