server:
  port: 8080

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none                        # no schema changes at runtime
  flyway:
    enabled: true                           # enable Flyway migrations
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always                  # more detail in prod health checks