server:
  port: 8080
#  ssl:
#    key-store: file:/config/keystore.p12
#    key-store-password: ${KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: tomcat
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json,application/javascript,text/css,text/html

spring:
  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update      # dev only; auto-create/alter tables
    show-sql: true
    open-in-view: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
#  security:
#    user:
#      name: ${ADMIN_USER:admin}
#      password: ${ADMIN_PASSWORD:?required}  # fail fast if not set

management:
  endpoints:
    web:
      exposure:
        include: scheduledtasks, health, metrics, prometheus   # Actuator endpoints

skyblock:
  bazaar:
    poll:
      enabled: false
      interval-seconds: 60 # 1 minute
    processing:
      price-move-threshold: 0.2 # 0.2%
      max-snapshot-gap-min: 5 # 5 minutes
      hourly:
        enabled: false
    retention:
      enabled: false
      interval-hours: 24 # 1 day
  catalog:
    enabled: true
    refresh-days: 7
    cron: "0 0 3 * * *"   # 03:00 every day

resilience4j.ratelimiter:
  instances:
    bazaarEndpoint:
      limitForPeriod: 200     # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full
    skyblockCatalog:
      limitForPeriod: 100    # calls
      limitRefreshPeriod: 1m  # per minute
      timeoutDuration: 0      # reject immediately when full

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html