global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]