name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-

          key: ''
      - name: Run unit & integration tests
        run: |
          ./gradlew clean test --no-daemon

      - name: Build application JAR
        run: |
          ./gradlew :core:bootJar --no-daemon

      - name: Build Docker image
        run: |
          docker build \
            -f infra/docker/core.Dockerfile \
            -t ghcr.io/${{ github.repository }}/core:sha-${{ github.sha }} \
            .

      # optionally push to GitHub Container Registry
      # - name: Log in to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push Docker image
      #   run: |
      #     docker push ghcr.io/${{ github.repository }}/core:sha-${{ github.sha }}
