name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew clean test --no-daemon

      # Build the runnable image
      - name: Build Docker image
        run: |
          docker build \
            -f infra/docker/core.Dockerfile \
            -t modernbazaar-core:ci-${{ github.run_id }} \
            .

      # Spin up a temporary Postgres the app can use
      - name: Create network
        run: docker network create bazaar-ci-net

      - name: Start Postgres
        run: |
          docker run -d --name pg-ci --network bazaar-ci-net \
            -e POSTGRES_DB=bazaar \
            -e POSTGRES_USER=bazaar \
            -e POSTGRES_PASSWORD=bazaar \
            -p 55432:5432 \
            postgres:16
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if docker exec pg-ci pg_isready -U bazaar >/dev/null 2>&1; then
              echo "Postgres is ready"; break
            fi
            sleep 2
          done

      - name: Run app container and wait for health
        env:
          # Keep memory modest for CI
          JAVA_OPTS: "-Xms128m -Xmx512m -XX:+UseG1GC -Xlog:gc*"
        run: |
          docker run -d --name bazaar-ci --network bazaar-ci-net \
            -e SPRING_PROFILES_ACTIVE=default \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://pg-ci:5432/bazaar \
            -e SPRING_DATASOURCE_USERNAME=bazaar \
            -e SPRING_DATASOURCE_PASSWORD=bazaar \
            -e BAZAAR_POLL_ENABLED=false \
            -e BAZAAR_RETENTION_ENABLED=false \
            -e JAVA_OPTS="$JAVA_OPTS" \
            -p 8080:8080 \
            modernbazaar-core:ci-${{ github.run_id }}

          echo "Waiting up to 90s for /actuator/health to report UP..."
          for i in {1..18}; do
            if curl -fs http://localhost:8080/actuator/health | grep -q '"status":"UP"'; then
              echo "✅ Service is healthy"; exit 0
            fi
            sleep 5
          done
          echo "❌ Service did not become healthy in time"
          echo "---- APP LOGS ----"
          docker logs bazaar-ci || true
          echo "---- PG LOGS ----"
          docker logs pg-ci || true
          exit 1

      - name: Tear down containers
        if: always()
        run: |
          docker rm -f bazaar-ci || true
          docker rm -f pg-ci || true
          docker network rm bazaar-ci-net || true
